/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 * This enum provides a list of all the user interface
 * text that needs to be loaded from the XML properties
 * file. By simply changing the XML file we could initialize
 * this application such that all UI controls are provided
 * in another language.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum CSGProp {
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    UPDATE_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT,
    SET_START_TIME_LABEL,
    SET_END_TIME_LABEL,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    TA_EMAIL_NOT_VALID_TITLE,
    TA_EMAIL_NOT_VALID_MESSAGE,
    STARTHOUR_NOT_VALID_TITLE,
    STARTHOUR_NOT_VALID_MESSAGE,
    ENDHOUR_NOT_VALID_TITLE,
    ENDHOUR_NOT_VALID_MESSAGE,
    OFFICE_HOURS_CONFLICT_TITLE,
    OFFICE_HOURS_CONFLICT_MESSAGE,
    
    MISSING_SECTION_TITLE,
    MISSING_SECTION_MESSAGE,
    MISSING_LOCATION_TITLE,
    MISSING_LOCATION_MESSAGE,
    MISSING_TIME_TITLE,
    MISSING_TIME_MESSAGE,
    MISSING_NAME_TITLE,
    MISSING_NAME_MESSAGE,
    MISSING_LINK_TITLE,
    MISSING_LINK_MESSAGE,
    MISSING_COLOR_TITLE,
    MISSING_COLOR_MESSAGE,
    MISSING_TEXTCOLOR_TITLE,
    MISSING_TEXTCOLOR_MESSAGE,
    MISSING_FIRSTNAME_TITLE,
    MISSING_FIRSTNAME_MESSAGE,
    MISSING_LASTNAME_TITLE,
    MISSING_LASTNAME_MESSAGE,
    MISSING_ROLE_TITLE,
    MISSING_ROLE_MESSAGE,
    MISSING_TEAM_TITLE,
    MISSING_TEAM_MESSAGE,
    MISSING_TITLE_TITLE,
    MISSING_TITLE_MESSAGE,
    MISSING_DATE_MESSAGE,
    MISSING_DATE_TITLE,
    
    STARTDATE_AFTER_TITLE,
    STARTDATE_AFTER_MESSAGE,
    STARTDATE_INVALID_TITLE,
    STARTDATE_INVALID_MESSAGE,
    ENDDATE_BEFORE_TITLE,
    ENDDATE_BEFORE_MESSAGE,
    ENDDATE_INVALID_TITLE,
    ENDDATE_INVALID_MESSAGE,
    
    
    CDTAB_HEADER,
    RECTAB_HEADER,
    SCHEDTAB_HEADER,
    TATAB_HEADER,
    PROJTAB_HEADER,
    
    COURSEINFO_HEADER,
    SUBJECT,
    NUMBER,
    SEMESTER,
    YEAR,
    TITLE,
    INSTRNAME,
    INSTRHOME,
    CHANGEEXPORTDIR,
    SITETEMP_HEADER,
    SITETEMP_NOTE,
    SELECTTEMPLATEDIR,
    SITEPAGES,
    USE_COL,
    NAVTITLE_COL,
    FILENAME_COL,
    SCRIPT_COL,
    PAGESTYLE_HEADER,
    BANNER,
    LEFTFOOT,
    RIGHTFOOT,
    STYLESHEET,
    STYLESHEET_NOTE,
    
    UNDERGRAD,
    
    SECTION_COL,
    INSTRUCTOR_COL,
    TIME_COL,
    LOCATION_COL,
    TA_COL,
    SECTION,
    INSTRUCTOR,
    TIME,
    LOCATION,
    TA,
    
    SCHEDULE,
    BOUNDARIES,
    STARTINGMON,
    ENDINGFRI,
    SCHEDULEITEMS,
    TYPE_COL,
    DATE_COL,
    TITLE_COL,
    TOPIC_COL,
    TYPE,
    DATE,
    TOPIC,
    LINK,
    CRITERIA,
    
    PROJECTS,
    TEAMS,
    NAME_COL,
    COLOR_COL,
    TEXTCOLOR_COL,
    LINK_COL,
    NAME,
    COLOR,
    TEXTCOLOR,
    STUDENTS,
    FIRSTNAME_COL,
    LASTNAME_COL,
    TEAM_COL,
    ROLE_COL,
    FIRSTNAME,
    LASTNAME,
    TEAM,
    ROLE,
    ADDEDIT,
    
    
    CHANGE_BUTTON,
    REMOVE_BUTTON,
    ADDEDIT_BUTTON,
    CLEAR_BUTTON,
}
    